slack:
  - id: "nuclei-fuzz"
    slack_channel: "nuclei-fuzz"
    slack_username: "nuclei-fuzz"
    slack_format: "{{data}}"
    slack_webhook_url: ""

discord:
  - id: "nuclei-fuzz1"
    discord_channel: "nuclei-fuzz"
    discord_username: "nuclei-fuzz"
    discord_format: "{{data}}"
    discord_webhook_url: "https://discord.com/api/webhooks/1223901339461877812/VdXtTYVcbTSJmfT2_ILMzvQAhndObPGw4xt1rk6FF_tiRIMrAep35aP78JehOjIDzOC5"
