slack:
  - id: "nuclei-fuzzer"
    slack_channel: "nuclei-fuzzer"
    slack_username: "nuclei-fuzzer"
    slack_format: "{{data}}"
    slack_webhook_url: ""

discord:
  - id: "nuclei-fuzzer2"
    discord_channel: "nuclei-fuzzer"
    discord_username: "nuclei-fuzzer"
    discord_format: "{{data}}"
    discord_webhook_url: "https://discord.com/api/webhooks/1226211766657089708/L26Q8XVc06zoqybD6v1_6SdyFEGKe2dOPvc96keAzrSnYHTNvgg3hSjQs4nrfjIH3JzO"
