slack:
  - id: "knoxss"
    slack_channel: "knoxss"
    slack_username: "knoxss"
    slack_format: "{{data}}"
    slack_webhook_url: ""

discord:
  - id: "knoxss2"
    discord_channel: "knoxss"
    discord_username: "knoxss"
    discord_format: "{{data}}"
    discord_webhook_url: "https://discord.com/api/webhooks/1223632416317640734/9IH0pPY1cjxztd8dKo1XU_cnNdWyYL7vD5_rNCQi03P9jXfGDfRtGVH52kqvHkPeTsNy"
